name:                eval-models
version:             0.1.0.0
github:              "dylnb/eval-models"
license:             BSD3
author:              "Dylan Bumford"
maintainer:          "example@example.com"
copyright:           "2020 Dylan Bumford"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dylnb/eval-models#readme>

dependencies:
- base >= 4.7 && < 5
- hvega
- ihaskell-hvega
- tyche
- extra
- text
# - ihaskell-tables
- mwc-probability
- monad-memo

# library:
#   source-dirs: src
